# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/dotBento.Bot"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Copenhagen"
    assignees:
      - "banner4422"

  - package-ecosystem: "nuget"
    directory: "/src/dotBento.WebApi"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Copenhagen"
    assignees:
      - "banner4422"

  - package-ecosystem: "nuget"
    directory: "/src/dotBento.Domain"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Copenhagen"
    assignees:
      - "banner4422"

  - package-ecosystem: "nuget"
    directory: "/src/dotBento.Infrastructure"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Copenhagen"
    assignees:
      - "banner4422"

  - package-ecosystem: "nuget"
    directory: "/src/dotBento.EntityFramework"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Copenhagen"
    assignees:
      - "banner4422"

  # (Optional) Test projects
  - package-ecosystem: "nuget"
    directory: "/tests/dotBento.Bot.Tests"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Copenhagen"
    assignees:
      - "banner4422"

  - package-ecosystem: "nuget"
    directory: "/tests/dotBento.WebApi.Tests"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Copenhagen"
    assignees:
      - "banner4422"

  - package-ecosystem: "nuget"
    directory: "/tests/dotBento.Infrastructure.Tests"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Copenhagen"
    assignees:
      - "banner4422"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: '06:00'
      timezone: 'Europe/Copenhagen'
    assignees:
      - 'banner4422'
  - package-ecosystem: "docker"
    directory: "src/" # Location of package manifests
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'Europe/Copenhagen'
    assignees:
      - 'banner4422'
