# This is an example of a docker-compose file that can be used to run the bot locally. 
services:
  bot-local:
    ports:
      - "5000:80"
    build: 
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
    networks:
      - web
      - bento_net
    env_file:
      - .env

  webapi:
    build:
      context: ./src/dotBento.WebApi
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
    ports:
      - "5027:5027"
    env_file:
      - .env
    networks:
      - web
      - bento_net

  sushii-image-server:
    image: ghcr.io/sushiibot/sushii-image-server:latest
    container_name: sushii-image-server
    restart: unless-stopped
    init: true
    cap_add:
      - SYS_ADMIN
    ports:
      - "3000:3000"
    networks:
      - bento_net

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bento
    ports:
      - "5432:5432"
    networks:
      - bento_net

  valkey-sta:
    image: valkey/valkey:9-alpine
    container_name: valkey-sta
    restart: unless-stopped
    command: [ "valkey-server", "--save", "", "--appendonly", "no" ]
    ports:
      - "6379:6379"
    networks:
      - bento_net

networks:
  web:
    internal: false
  bento_net:
    external: false