# This is equivalent to the production docker-compose file
services:
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - "9091:9091"
    networks:
      - bento_net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    networks:
      - bento_net

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - bento_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - bento_net

  # Exposes system metrics to prometheus
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - bento_net
        
  # --- Valkey for Production ---
  valkey-prod:
    image: valkey/valkey:9-alpine
    container_name: valkey-prod
    restart: unless-stopped
    command: [ "valkey-server", "--save", "", "--appendonly", "no" ]
    networks:
      - bento_net
        
  # --- Valkey for Staging --- (optional if you want a staging environment)
#  valkey-sta:
#    image: valkey/valkey:9-alpine
#    container_name: valkey-sta
#    restart: unless-stopped
#    command: [ "valkey-server", "--save", "", "--appendonly", "no" ]
#    networks:
#      - bento_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - bento_net

  sushii-image-server:
    image: ghcr.io/sushiibot/sushii-image-server:latest
    container_name: sushii-image-server
    restart: unless-stopped
    init: true
    cap_add:
      - SYS_ADMIN
    expose:
      - '3000'
    networks:
      - bento_net

  # Production Bot Service
  bot-prod:
    image: ghcr.io/thebentobot/dotbento
    container_name: bot-prod
    restart: unless-stopped
    env_file:
      - .env-prod
    expose:
      - '8080'
    networks:
      - bento_net
      - web

  # PostgreSQL Database for Staging Bot
#  postgres:
#    image: postgres
#    container_name: postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_USER: username
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: bento
#    networks:
#      - bento_net

  # Staging Bot Service - optional if you want a staging environment
#  bot-sta:
#    image: ghcr.io/thebentobot/dotbento:staging
#    container_name: bot-sta
#    restart: unless-stopped
#    env_file:
#      - .env-sta
#    depends_on:
#      - postgres
#    expose:
#      - '8080'
#    networks:
#      - bento_net
#      - web

  # WebAPI
  webapi:
    image: ghcr.io/thebentobot/dotbento-webapi
    container_name: webapi
    restart: unless-stopped
    env_file:
      - .env-webapi
    ports:
      - "8080:8080"
    networks:
      - bento_net
      - web

networks:
  web:
    internal: false
  bento_net:
    external: false